# Generated by Django 3.0.1 on 2020-01-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
