# Generated by Django 3.0.1 on 2020-01-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Have_Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('rent', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
